services:
  app:
    image: hello-front-dev
    build:
      context: . # контекст сборки — текущая папка
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 5173:5173
    container_name: hello-front-dev
